name: tag
version: '1.0-SNAPSHOT'
main: uk.cloudmc.microwavedram.tag.Tag
api-version: '1.20'
depend: ["LuckPerms"]
folia-supported: true

commands:
  tag:
    description: Toggle the tag state of a player
    usage: "/tag <player>"
    permission: tag.tag   